### ISSUE TITLE
[frontend]  chage the icon and title of the page

### ISSUE THREAD

**Issue by ravellys** [LTCRX/ltcrx.github.io#3]
# What
You must change the Icon and title (React App) of the page

![Image](https://github.com/LTCRX/ltcrx.github.io/assets/57733801/24ad45ee-f869-42ef-ae70-81305f329744)

using this image:

![Image](https://github.com/LTCRX/ltcrx.github.io/assets/57733801/6892f873-926f-4c0c-9cd7-11cee9a1d9fc)

**Comment by rohit-chaware** [comment]
@ravellys I would like to work on this issue.
